# -*- coding: utf-8 -*-
"""TextDivide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twh6b1SZB-0ouqvnHMGJajcNV_F6Z0ED
"""


class TextDivide:
    # def __init__(self, lecture_string, folder_name, start_lecture, end_lecture):
    #     self.lecture_string = lecture_string
    #     self.folder_name = folder_name
    #     self.start_lecture = start_lecture
    #     self.end_lecture = end_lecture

    def Text_Title_Generator(start_lecture, end_lecture):
        # start_lecture = 2
        # end_lecture = 51
        lecture_string = []

        for i in range(start_lecture, end_lecture + 1):
            if i < 10:
                lecture_string.append("0" + str(i) + "강")
            else:
                lecture_string.append(str(i) + "강")

        return lecture_string

    def Text_Contents_Divider(text, folder_name, text_num):
        index = 0
        result = []
        # text_num에 지정된 글자수로 나눕니다.
        while (index + text_num < len(text)):
            i = 0
            while (text[index + text_num - i] != "."):
                i += 1

            result.append(text[index:index + text_num - i + 1])
            index += text_num - i + 1

        result.append(text[index:])
        print("결과 : ", result)
        print("나눠진 갯수 : ", len(result))
        print("원 문장의 총 길이 : ", len(text))

        # 나눈 글을 저장합니다.
        # for i in range(len(result)):
        # with open("/content/drive/MyDrive/txt_data/" + folder_name + "/" + folder_name + "-" + str(i) + ".txt", "w") as text_file:
        #     text_file.write(result[i])

        return len(result)  # KoBart_Run_Multi_Text에서 OrNum의 값입니다.